### Imports

In [1]:
import os
import json
import tempfile
import subprocess
from itertools import islice

import pandas as pd
from huggingface_hub import list_repo_files, hf_hub_download

/Users/aneeshkalla/anaconda3/envs/driving/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Template Code

In [2]:
#NOTE: YOU WILL NEED TO MAKE SURE YOU HAVE THE FILE "credentials.json" IN ORDER TO ACCESS THE API
import io
from googleapiclient.http import MediaIoBaseDownload



from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
import pickle
import os
import io # Required for downloading file content
import mimetypes # Required for guessing MIME type during upload
#NOTE: You might have to do pip install on a few google libraries before you can use this code
# Define the permissions scope
# 'drive.file' scope grants access only to files created or opened by this app.
SCOPES = ['https://www.googleapis.com/auth/drive']

def get_drive_service():
    """Authenticates the user and returns the Google Drive API service object."""
    creds = None
    # 1. Load existing credentials (token.pickle)
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
            
    # 2. If no valid creds, refresh or perform OAuth login
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            # Refresh expired token silently
            creds.refresh(Request())
        else:
            # Perform full login flow, requires 'credentials.json' in the same directory
            flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
            
        # 3. Save the new/refreshed token
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    service = build('drive', 'v3', credentials=creds)
    return service

def upload_to_drive(file_path, folder_id=None):
    """
    Uploads a file to Google Drive.
    
    :param file_path: The path to the local file to upload.
    :param folder_id: The Google Drive ID of the target folder. None for root.
    :return: The ID of the uploaded file, or None on failure.
    """
    try:
        service = get_drive_service()
        
        # 1. Guess the MIME type from the file extension
        mime_type, _ = mimetypes.guess_type(file_path)
        if not mime_type:
            mime_type = 'application/octet-stream' # Default if type cannot be guessed

        # 2. Set file metadata (name and parent folder)
        file_metadata = {'name': os.path.basename(file_path)}
        if folder_id:
            file_metadata['parents'] = [folder_id]
            
        # 3. Create media object for upload
        media = MediaFileUpload(file_path, mimetype=mime_type, resumable=True)
        
        # 4. Execute the upload
        uploaded = service.files().create(
            body=file_metadata, 
            media_body=media, 
            fields='id'
        ).execute()
        
        file_id = uploaded.get('id')
        print(f"✅ Successfully uploaded '{os.path.basename(file_path)}'. ID: {file_id}")
        return file_id
        
    except FileNotFoundError:
        print(f"❌ Error: The file was not found at path: {file_path}")
        return None
    except Exception as e:
        print(f"❌ An error occurred during upload: {e}")
        return None

def download_from_drive(file_id, local_file_path):
    """
    Downloads a file from Google Drive using its file ID.
    TO FIND THE FILE ID ON GOOGLE DRIVE, SIMPLY GO TO THE GOOGLE DRIVE WEBSITE, CLICK ON THE THING YOU WANT, AND THE LONG STRING OF NUMBERS AND CHARACTERS AFTER "/folders" IN THE WEB ADDRESS IS IT
    :param file_id: The ID of the file to download from Drive.
    :param local_file_path: The path and name to save the file locally.
    :return: True on success, False on failure.
    """
    try:
        service = get_drive_service()

        # 1. Execute the download request using alt='media'
        request = service.files().get_media(fileId=file_id, supportsAllDrives=True)
        fh = io.BytesIO()
        downloader = MediaIoBaseDownload(fh, request)

        done = False
        while not done:
            status, done = downloader.next_chunk()
            if status:
                print(f"Downloading... {int(status.progress() * 100)}%")

        # ✅ Extract raw bytes from the BytesIO buffer
        file_content = fh.getvalue()

        if isinstance(file_content, dict):
            print("⚠️ Drive returned a dictionary instead of bytes — likely an error:")
            print(file_content)   # <-- this shows the error message from Drive
            return False          # Stop here before writing bad data

        # 2. Write the downloaded byte content to a local file
        with open(local_file_path, 'wb') as f:
            f.write(file_content)

        print(f"⬇️ Successfully downloaded file ID {file_id} to '{local_file_path}'.")
        return True

    except Exception as e:
        print(f"❌ An error occurred during download for file ID {file_id}: {e}", flush=True)
        return False

In [3]:
import os
import cv2
from huggingface_hub import HfFileSystem

# === CONFIG ===
TEMP_DIR = "temp_videos"
os.makedirs(TEMP_DIR, exist_ok=True)

HF_TOKEN = os.environ.get("HF_TOKEN")  # set via environment variable
fs = HfFileSystem(token=HF_TOKEN)

def load_video(row):
    """
    Given a DataFrame row (with 'source' and 'filepath'),
    downloads the video if needed and returns the local file path.

    - if source == 'huggingface': downloads via fsspec (fs) into TEMP_DIR
    - if source == 'googledrive': downloads using other_info['fileID'] and the existing
      Google Drive helper functions (download_from_drive)
    """
    source = row["source"]
    filepath = row["filepath"]

    # Always keep the same filename
    filename = os.path.basename(filepath)
    local_path = os.path.join(TEMP_DIR, filename)

    if source == "huggingface":
        # Download if not already present
        if not os.path.exists(local_path):
            print(f"Downloading {filepath} from Hugging Face...")
            with fs.open(filepath, "rb") as src, open(local_path, "wb") as dst:
                dst.write(src.read())
        return os.path.abspath(local_path)

    elif source == "googledrive":
        # Expect 'other_info' to contain the file ID
        try:
            other_info = row["other_info"]
            file_id = other_info["fileID"]
        except Exception:
            raise ValueError("For 'googledrive' source, row['other_info']['fileID'] is required.")

        # Download only if not already saved locally
        if not os.path.exists(local_path):
            print(f"Downloading {filename} from Google Drive (fileID={file_id})...")
            success = download_from_drive(file_id, local_path)
            if not success:
                raise RuntimeError(f"Failed to download file ID {file_id} from Google Drive.")

        return os.path.abspath(local_path)

    else:
        raise NotImplementedError(f"Source '{source}' not supported yet.")

def script1(video_path):
    """
    Simple video player using OpenCV.
    Plays until the end or until 'q' is pressed.
    """
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"Error: Could not open {video_path}")
        return

    print(f"Playing video: {video_path}")
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        cv2.imshow("Video", frame)
        if cv2.waitKey(25) & 0xFF == ord("q"):
            break

    cap.release()
    cv2.destroyAllWindows()

def delete_video(video_path):
    """
    Deletes a local video file (e.g., one downloaded by load_video()).
    Only allows deletion inside the temp_videos folder for safety.
    """
    abs_path = os.path.abspath(video_path)
    temp_dir_abs = os.path.abspath(TEMP_DIR)

    # Ensure safety: only delete inside temp_videos
    if abs_path.startswith(temp_dir_abs) and os.path.exists(abs_path):
        os.remove(abs_path)
        print(f"Deleted: {abs_path}")
    else:
        print(f"Skipped deletion (unsafe path): {abs_path}")


# === Example usage ===
# import pandas as pd
# df = pd.read_hdf("nexar_train_prepared.h5", key="data")
# row = df.iloc[0]
# local_path = load_video(row)
# script1(local_path)
# delete_video(local_path)

### Example Usage

In [5]:
#loading up a saved dataframe
import pandas as pd
df = pd.read_hdf("nexar_train_prepared.h5", key="data")
df

,filepath,source,event_time,event_description,split,other_info
0,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,19.500,collision,train,"{""time_of_alert"": 18.633, ""light_conditions"": ..."
1,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,19.800,collision,train,"{""time_of_alert"": 19.233, ""light_conditions"": ..."
2,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,20.101,collision,train,"{""time_of_alert"": 20.068, ""light_conditions"": ..."
3,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,19.267,collision,train,"{""time_of_alert"": 18.333, ""light_conditions"": ..."
4,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,21.146,collision,train,"{""time_of_alert"": 18.196, ""light_conditions"": ..."
...,...,...,...,...,...,...
1495,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
1496,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
1497,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
1498,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
1499,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."

In [6]:
row = df.iloc[0]
local_path = load_video(row)
script1(local_path) #random function that displays the video clip
delete_video(local_path)

Playing video: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00822.mp4
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00822.mp4

In [ ]:
import pandas as pd
import concurrent.futures

def script2(video_path):
    """
    Return the length of a video in seconds as a float.
    """
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"Error: Could not open {video_path}")
        return None

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
    cap.release()

    if fps <= 0 or frame_count <= 0:
        return None
    return float(frame_count / fps)


# === Batch processing ===
input_path = "nexar_train_prepared.h5"
output_path = "output.h5"
df = pd.read_hdf(input_path, key="data")
results = []
n = 10  # number of clips per batch
for i in range(3):  # run 3 batches
    start = i * n
    end = start + n
    if start >= len(df):
        break
    batch = df.iloc[start:end]
    # Load videos concurrently
    with concurrent.futures.ThreadPoolExecutor(max_workers=n) as executor:
        futures = {executor.submit(load_video, row): idx for idx, row in batch.iterrows()}
        local_paths = {}
        for future in concurrent.futures.as_completed(futures):
            idx = futures[future]
            try:
                local_paths[idx] = future.result()
            except Exception as e:
                print(f"Error loading row {idx}: {e}")
    for idx, local_path in local_paths.items():
        clip_length = script2(local_path)
        row_data = batch.loc[idx].to_dict()
        row_data["output"] = clip_length
        results.append(row_data)
        delete_video(local_path)

output_df = pd.DataFrame(results)
output_df.to_hdf(output_path, key="data", mode="w")

print(f"✅ Output saved to {output_path}")
print(output_df.head())

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00822.mp4 from Hugging Face...Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00208.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00072.mp4 from Hugging Face...

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00128.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00205.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00408.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00948.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00457.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00471.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00900.mp4 from Hugging Face...
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00408.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00128.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00072.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00471.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00205.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00822.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00208.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00457.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00900.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00948.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00333.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00841.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00564.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00245.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00171.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00795.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00372.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00938.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00641.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00884.mp4 from Hugging Face...
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00641.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00841.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00938.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00333.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00245.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00171.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00372.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00884.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00795.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00564.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00927.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00378.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00010.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00238.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00876.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00313.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00098.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00516.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00357.mp4 from Hugging Face...
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00903.mp4 from Hugging Face...
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00378.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00238.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00313.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00927.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00010.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00516.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00357.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00098.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00876.mp4
Deleted: /Users/aneeshkalla/Desktop/AI_driving_tool/temp_videos/00903.mp4
✅ Output saved to output.h5
                                            filepath       source  event_time  \
0  hf://datasets/nexar-ai/nexar_collision_predict...  huggingface      19.953
1  hf://datasets/nexar-ai/nexar_collision_predict...  huggingface      19.267
2  hf://datasets/nexar-ai/nexar_collision_predict...  huggingface      20.101
3  hf://datasets/nexar-ai/nexar_collision_predict...  huggingface      19.833
4  hf://datasets/nexar-ai/nexar_collision_predict...  huggingface      21.146

  event_description  split                                         other_info  \
0         collision  train  {"time_of_alert": 17.551, "light_conditions": ...
1         collision  train  {"time_of_alert": 18.333, "light_conditions": ...
2         collision  train  {"time_of_alert": 20.068, "light_conditions": ...
3         collision  train  {"time_of_alert": 18.267, "light_conditions": ...
4         collision  train  {"time_of_alert": 18.196, "light_conditions": ...

      output
0  32.341137
1  40.266667
2  40.393443
3  42.066667
4  39.344262

In [ ]:
# Example: one-row DataFrame for testing
data = [{
    "filepath": "00822.mp4",  # name of the file in Drive
    "source": "googledrive",        # triggers the Drive branch in load_video()
    "event_time": None,
    "event_description": "test_download",
    "split": "demo",
    "other_info": {"fileID": "18ZrK_DsUHZLjJ7qPDDHECaVmcp-fthK8"}  # your file ID
}]
df = pd.DataFrame(data)
# Preview to confirm
print(df)
# ✅ Use your load_video() function
row = df.iloc[0]
local_path = load_video(row)
print("\nDownloaded local file path:", local_path)

    filepath       source event_time event_description split  \
0  00822.mp4  googledrive       None     test_download  demo

                                        other_info
0  {'fileID': '18ZrK_DsUHZLjJ7qPDDHECaVmcp-fthK8'}

Downloaded local file path: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00822.mp4

In [ ]:

uploaded_id = upload_to_drive("/Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00822.mp4", folder_id="1dtgKrSeaAyv4WrbGVr8zeoKH_7B_7bPg")

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=221407270655-90npb4apkqrkpfmpehtn4hpfb3971kvn.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A50266%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=TcPl5Z1UcuktxBBo7j1n8CDaBO7F5v&access_type=offline
✅ Successfully uploaded '00822.mp4'. ID: 1CKFu7T83RZNehEPb-IfxpgZkfo-i1TN6

### DINO basic setup

In [4]:
from pathlib import Path


def collision_video_frames(row, frame_interval_seconds=0.5, impact_window_seconds=2.0):
    """Load a clip, sample frames, store them, and return their metadata as a DataFrame."""
    if frame_interval_seconds <= 0:
        raise ValueError("frame_interval_seconds must be > 0")
    if impact_window_seconds < 0:
        raise ValueError("impact_window_seconds must be >= 0")

    video_path = load_video(row)
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video at {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    if not fps or fps <= 0:
        cap.release()
        delete_video(video_path)
        raise RuntimeError("Video FPS could not be determined")

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frame_step = max(1, int(round(frame_interval_seconds * fps)))
    impact_time = row.get("event_time") if hasattr(row, "get") else row["event_time"]
    impact_time = float(impact_time) if impact_time is not None else None
    impact_window_end = None if impact_time is None else impact_time + float(impact_window_seconds)

    images_dir = Path("frames") / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    video_name = Path(video_path).stem
    rows = []

    try:
        for frame_idx in range(0, total_frames, frame_step):
            cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
            success, frame = cap.read()
            if not success:
                break

            timestamp = frame_idx / fps

            if impact_time is not None and impact_window_end is not None and timestamp > impact_window_end:
                break  # stop once we're past the post-impact window

            label = 0
            if impact_time is not None:
                label = int(impact_time <= timestamp <= impact_window_end)

            filename = f"{video_name}_{round(timestamp, 3)}s.jpg"
            frame_path = images_dir / filename
            cv2.imwrite(str(frame_path), frame)

            rows.append(
                {
                    "video_name": video_name,
                    "frame_path": str(frame_path),
                    "frame_index": frame_idx,
                    "time_seconds": round(timestamp, 3),
                    "label": label,
                }
            )
    finally:
        cap.release()
        delete_video(video_path)

    return pd.DataFrame(rows)

In [ ]:
'''
# Demo run for the first Nexar collision clip
if "df" not in globals():
    df = pd.read_hdf("nexar_train_prepared.h5", key="data")

sample_row = df.iloc[0]
frames_df = collision_video_frames(
    sample_row,
    frame_interval_seconds=0.2,
    impact_window_seconds=2.0,
)
frames_df
'''

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00822.mp4 from Hugging Face...
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00822.mp4

,video_name,frame_path,frame_index,time_seconds,label
0,00822,frames/images/00822_0.0s.jpg,0,0.0,0
1,00822,frames/images/00822_0.2s.jpg,6,0.2,0
2,00822,frames/images/00822_0.4s.jpg,12,0.4,0
3,00822,frames/images/00822_0.6s.jpg,18,0.6,0
4,00822,frames/images/00822_0.8s.jpg,24,0.8,0
...,...,...,...,...,...
103,00822,frames/images/00822_20.6s.jpg,618,20.6,1
104,00822,frames/images/00822_20.8s.jpg,624,20.8,1
105,00822,frames/images/00822_21.0s.jpg,630,21.0,1
106,00822,frames/images/00822_21.2s.jpg,636,21.2,1
107,00822,frames/images/00822_21.4s.jpg,642,21.4,1

In [5]:
import os
import urllib
from PIL import Image

import torch
import torchvision.transforms.functional as TF
import numpy as np

print("PyTorch version:", torch.__version__)

# --- device selection for Mac ---
if torch.backends.mps.is_available():
    DEVICE = "mps"
    print("Using Apple Silicon GPU (MPS).")
else:
    DEVICE = "cpu"
    print("Using CPU.")

DEVICE

PyTorch version: 2.9.1
Using Apple Silicon GPU (MPS).

'mps'

In [6]:
DINOV3_REPO = "facebookresearch/dinov3"
#MODEL_NAME = "dinov3_vith16plus"  # HP model
MODEL_NAME = "dinov3_vits16plus"


# Optional: allow user to override with a local clone
DINOV3_LOCATION = os.getenv("DINOV3_LOCATION", DINOV3_REPO)
SOURCE = "local" if DINOV3_LOCATION != DINOV3_REPO else "github"

print("Loading model:", MODEL_NAME)
print("From:", DINOV3_LOCATION, "| source:", SOURCE)

model = torch.hub.load(
    repo_or_dir=DINOV3_LOCATION,
    model=MODEL_NAME,
    source=SOURCE,
)

model = model.to(DEVICE).eval()
print("Model loaded on:", DEVICE)

Loading model: dinov3_vits16plus
From: facebookresearch/dinov3 | source: github

Using cache found in /Users/aneeshkalla/.cache/torch/hub/facebookresearch_dinov3_main

Model loaded on: mps

In [7]:
PATCH_SIZE = 16
IMAGE_SIZE = 768

IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

def load_image_from_url(url: str) -> Image.Image:
    with urllib.request.urlopen(url) as f:
        return Image.open(f).convert("RGB")

def resize_transform(
    image: Image.Image,
    image_size: int = IMAGE_SIZE,
    patch_size: int = PATCH_SIZE,
):
    w, h = image.size
    h_patches = image_size // patch_size
    w_patches = int((w * image_size) / (h * patch_size))
    return TF.to_tensor(
        TF.resize(image, (h_patches * patch_size, w_patches * patch_size))
    )

def normalize_image(t: torch.Tensor) -> torch.Tensor:
    return TF.normalize(t, mean=IMAGENET_MEAN, std=IMAGENET_STD)

In [8]:
# Number of layers for DINOv3 variants
MODEL_TO_NUM_LAYERS = {
    "dinov3_vits16": 12,
    "dinov3_vits16plus": 12,
    "dinov3_vitb16": 12,
    "dinov3_vitl16": 24,
    "dinov3_vith16plus": 32,
    "dinov3_vit7b16": 40,
}

N_LAYERS = MODEL_TO_NUM_LAYERS[MODEL_NAME]

def dino_forward_tokens(
    model,
    img_batch: torch.Tensor,
    layers=None,
    device=DEVICE,
):
    """
    Runs DINOv3 and returns a dict for a batch input:
      { layer_index: {"cls": (B, D), "patch": (B, N_patches, D)} }
    """

    if layers is None:
        layers = [N_LAYERS - 1]  # last layer only

    img_batch = img_batch.to(device)

    with torch.no_grad():  # CPU / MPS friendly
        feats = model.get_intermediate_layers(
            img_batch,
            n=layers,
            reshape=False,
            norm=True,
        )

    outputs = {}

    for layer_idx, tok in zip(layers, feats):
        tok = tok.detach().cpu()  # (B, num_tokens, dim)
        cls_tok = tok[:, 0, :]
        patch_tok = tok[:, 1:, :]
        outputs[layer_idx] = {
            "cls": cls_tok,
            "patch": patch_tok,
        }

    return outputs

In [22]:
# Prepare frames for DINO processing
batch_size = 1
all_frame_paths = frames_df['frame_path'].tolist()
images = []
for path in all_frame_paths:
    img = Image.open(path).convert('RGB')
    img_t = normalize_image(resize_transform(img))
    images.append(img_t)

In [23]:
import tqdm

cls_tokens_list = []
patch_tokens_list = []

for start_idx in tqdm.tqdm(range(0, len(images), batch_size)):
    batch_imgs = torch.stack(images[start_idx:start_idx + batch_size], dim=0)
    print(f'Processing batch from {start_idx} to {start_idx + batch_imgs.shape[0] - 1}')

    batch_tokens = dino_forward_tokens(model, batch_imgs, layers=[N_LAYERS - 1])
    layer_idx = list(batch_tokens.keys())[0]
    cls_tokens_list.append(batch_tokens[layer_idx]['cls'])
    patch_tokens_list.append(batch_tokens[layer_idx]['patch'])

cls_tokens = torch.cat(cls_tokens_list, dim=0)
patch_tokens = torch.cat(patch_tokens_list, dim=0)
print(f'CLS tokens shape: {cls_tokens.shape}')
print(f'Patch tokens shape: {patch_tokens.shape}')

# Attach tokens back to frames_df
frames_df['cls_token'] = list(cls_tokens.numpy())
frames_df['patch_tokens'] = list(patch_tokens.numpy())
frames_df.head()

  0%|          | 0/41 [00:00<?, ?it/s]

Processing batch from 0 to 0

  2%|▏         | 1/41 [00:00<00:35,  1.14it/s]

Processing batch from 1 to 1

  5%|▍         | 2/41 [00:01<00:31,  1.22it/s]

Processing batch from 2 to 2

  7%|▋         | 3/41 [00:02<00:31,  1.19it/s]

Processing batch from 3 to 3

 10%|▉         | 4/41 [00:03<00:31,  1.18it/s]

Processing batch from 4 to 4

 12%|█▏        | 5/41 [00:04<00:29,  1.22it/s]

Processing batch from 5 to 5

 15%|█▍        | 6/41 [00:04<00:27,  1.26it/s]

Processing batch from 6 to 6

 17%|█▋        | 7/41 [00:05<00:27,  1.25it/s]

Processing batch from 7 to 7

 20%|█▉        | 8/41 [00:06<00:26,  1.25it/s]

Processing batch from 8 to 8

 22%|██▏       | 9/41 [00:07<00:25,  1.24it/s]

Processing batch from 9 to 9

 24%|██▍       | 10/41 [00:08<00:24,  1.24it/s]

Processing batch from 10 to 10

 27%|██▋       | 11/41 [00:08<00:23,  1.26it/s]

Processing batch from 11 to 11

 29%|██▉       | 12/41 [00:09<00:22,  1.26it/s]

Processing batch from 12 to 12

 32%|███▏      | 13/41 [00:10<00:22,  1.24it/s]

Processing batch from 13 to 13

 32%|███▏      | 13/41 [00:11<00:24,  1.15it/s]

KeyboardInterrupt:

# Training Dino

In [4]:
#helper functions

from pathlib import Path
import tqdm
import os
import urllib
from PIL import Image

import torch
import torchvision.transforms.functional as TF
import numpy as np
import os
import urllib
from PIL import Image

import torch
import torchvision.transforms.functional as TF
import numpy as np

print("PyTorch version:", torch.__version__)

# --- device selection for Mac ---
if torch.backends.mps.is_available():
    DEVICE = "mps"
    print("Using Apple Silicon GPU (MPS).")
else:
    DEVICE = "cpu"
    print("Using CPU.")

DEVICE

def collision_video_frames(row, frame_interval_seconds=0.5, impact_window_seconds=2.0):
    if frame_interval_seconds <= 0:
        raise ValueError("frame_interval_seconds must be > 0")
    if impact_window_seconds < 0:
        raise ValueError("impact_window_seconds must be >= 0")

    video_path = load_video(row)
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video at {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    if not fps or fps <= 0:
        cap.release()
        delete_video(video_path)
        raise RuntimeError("Video FPS could not be determined")

    frame_step = max(1, int(round(frame_interval_seconds * fps)))
    impact_time = float(row["event_time"]) if row["event_time"] is not None else None
    impact_window_end = None if impact_time is None else impact_time + float(impact_window_seconds)

    images_dir = Path("frames") / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    video_name = Path(video_path).stem
    rows = []

    try:
        frame_idx = 0
        while True:
            success, frame = cap.read()
            if not success:
                break

            if frame_idx % frame_step != 0:
                frame_idx += 1
                continue

            timestamp = frame_idx / fps

            if impact_time is not None and impact_window_end is not None and timestamp > impact_window_end:
                break

            label = 0
            if impact_time is not None:
                label = int(impact_time <= timestamp <= impact_window_end)

            filename = f"{video_name}_{round(timestamp, 3)}s.jpg"
            frame_path = images_dir / filename
            cv2.imwrite(str(frame_path), frame, [int(cv2.IMWRITE_JPEG_QUALITY), 90])

            rows.append(
                {
                    "video_name": video_name,
                    "frame_path": str(frame_path),
                    "frame_index": frame_idx,
                    "time_seconds": round(timestamp, 3),
                    "label": label,
                }
            )

            frame_idx += 1
    finally:
        cap.release()
        delete_video(video_path)

    return pd.DataFrame(rows)

'''
example usage

if "df" not in globals():
    df = pd.read_hdf("nexar_train_prepared.h5", key="data")

sample_row = df.iloc[0]
frames_df = collision_video_frames(
    sample_row,
    frame_interval_seconds=0.2,
    impact_window_seconds=2.0,
)
frames_df


'''

PATCH_SIZE = 16
IMAGE_SIZE = 768

IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

def load_image_from_url(url: str) -> Image.Image:
    with urllib.request.urlopen(url) as f:
        return Image.open(f).convert("RGB")

def resize_transform(
    image: Image.Image,
    image_size: int = IMAGE_SIZE,
    patch_size: int = PATCH_SIZE,
):
    w, h = image.size
    h_patches = image_size // patch_size
    w_patches = int((w * image_size) / (h * patch_size))
    return TF.to_tensor(
        TF.resize(image, (h_patches * patch_size, w_patches * patch_size))
    )

def normalize_image(t: torch.Tensor) -> torch.Tensor:
    return TF.normalize(t, mean=IMAGENET_MEAN, std=IMAGENET_STD)




DINOV3_REPO = "facebookresearch/dinov3"
#MODEL_NAME = "dinov3_vith16plus"  # HP model
MODEL_NAME = "dinov3_vits16plus"


# Optional: allow user to override with a local clone
DINOV3_LOCATION = os.getenv("DINOV3_LOCATION", DINOV3_REPO)
SOURCE = "local" if DINOV3_LOCATION != DINOV3_REPO else "github"

print("Loading model:", MODEL_NAME)
print("From:", DINOV3_LOCATION, "| source:", SOURCE)

model = torch.hub.load(
    repo_or_dir=DINOV3_LOCATION,
    model=MODEL_NAME,
    source=SOURCE,
)

model = model.to(DEVICE).eval()
print("Model loaded on:", DEVICE)

MODEL_TO_NUM_LAYERS = {
    "dinov3_vits16": 12,
    "dinov3_vits16plus": 12,
    "dinov3_vitb16": 12,
    "dinov3_vitl16": 24,
    "dinov3_vith16plus": 32,
    "dinov3_vit7b16": 40,
}

N_LAYERS = MODEL_TO_NUM_LAYERS[MODEL_NAME]

'''
example dino usage

if layers is None:
        layers = [N_LAYERS - 1]  # last layer only

    img_batch = img_batch.to(device)

    with torch.no_grad():  # CPU / MPS friendly
        feats = model.get_intermediate_layers(
            img_batch,
            n=layers,
            reshape=False,
            norm=True,
        )

    outputs = {}

    for layer_idx, tok in zip(layers, feats):
        tok = tok.detach().cpu()  # (B, num_tokens, dim)
        cls_tok = tok[:, 0, :]
        patch_tok = tok[:, 1:, :]
        outputs[layer_idx] = {
            "cls": cls_tok,
            "patch": patch_tok,
        }

'''

PyTorch version: 2.9.1
Using Apple Silicon GPU (MPS).
Loading model: dinov3_vits16plus
From: facebookresearch/dinov3 | source: github

Using cache found in /Users/aneeshkalla/.cache/torch/hub/facebookresearch_dinov3_main

Model loaded on: mps

'\nexample dino usage\n\nif layers is None:\n        layers = [N_LAYERS - 1]  # last layer only\n\n    img_batch = img_batch.to(device)\n\n    with torch.no_grad():  # CPU / MPS friendly\n        feats = model.get_intermediate_layers(\n            img_batch,\n            n=layers,\n            reshape=False,\n            norm=True,\n        )\n\n    outputs = {}\n\n    for layer_idx, tok in zip(layers, feats):\n        tok = tok.detach().cpu()  # (B, num_tokens, dim)\n        cls_tok = tok[:, 0, :]\n        patch_tok = tok[:, 1:, :]\n        outputs[layer_idx] = {\n            "cls": cls_tok,\n            "patch": patch_tok,\n        }\n\n'

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix
from concurrent.futures import ThreadPoolExecutor, as_completed
import numpy as np
import tqdm

# Load the prepared collision DataFrame if not already present
if "df" not in globals():
    df = pd.read_hdf("nexar_train_prepared.h5", key="data")

train_clips_df, test_clips_df = train_test_split(
    df, test_size=0.2, random_state=42, shuffle=True
)
print(f"Train clips: {len(train_clips_df)} | Test clips: {len(test_clips_df)}")

Train clips: 1200 | Test clips: 300

In [6]:
from concurrent.futures import ThreadPoolExecutor, as_completed


def build_frames_df(
    clips_df,
    frame_interval_seconds=0.5,
    impact_window_seconds=2.0,
    max_workers=8,
):
    def process_clip(clip_row):
        return collision_video_frames(
            clip_row,
            frame_interval_seconds=frame_interval_seconds,
            impact_window_seconds=impact_window_seconds,
        )

    clip_rows = list(clips_df.iterrows())
    if not clip_rows:
        return pd.DataFrame(columns=[
            "video_name",
            "frame_path",
            "frame_index",
            "time_seconds",
            "label",
        ])

    frame_parts = []
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(process_clip, row): idx for idx, (_, row) in enumerate(clip_rows)}
        for future in tqdm.tqdm(as_completed(futures), total=len(futures)):
            frame_parts.append(future.result())

    return pd.concat(frame_parts, ignore_index=True)
'''
train_frames_df = build_frames_df(train_clips_df)
test_frames_df = build_frames_df(test_clips_df)

print("Train frames:", len(train_frames_df), "| label counts:", train_frames_df["label"].value_counts())
train_frames_df.to_hdf("frames.h5", key="train", mode="w")

print("Test frames:", len(test_frames_df), "| label counts:", test_frames_df["label"].value_counts())
test_frames_df.to_hdf("frames.h5", key="test", mode="a")


# Persist extracted frame metadata for reuse
print("Saved frame DataFrames to frames.h5 (keys: train, test)")
'''

'\ntrain_frames_df = build_frames_df(train_clips_df)\ntest_frames_df = build_frames_df(test_clips_df)\n\nprint("Train frames:", len(train_frames_df), "| label counts:", train_frames_df["label"].value_counts())\ntrain_frames_df.to_hdf("frames.h5", key="train", mode="w")\n\nprint("Test frames:", len(test_frames_df), "| label counts:", test_frames_df["label"].value_counts())\ntest_frames_df.to_hdf("frames.h5", key="test", mode="a")\n\n\n# Persist extracted frame metadata for reuse\nprint("Saved frame DataFrames to frames.h5 (keys: train, test)")\n'

In [9]:
frames_store = "frames.h5"  # adjust path if needed
train_frames_df = pd.read_hdf(frames_store, key="train")
test_frames_df = pd.read_hdf(frames_store, key="test")
print(len(train_frames_df), "train frames loaded")
print(len(test_frames_df), "test frames loaded")

70628 train frames loaded
17715 test frames loaded

In [7]:
from torch.utils.data import Dataset, DataLoader, Sampler
from PIL import Image


def frame_to_tensor(img: Image.Image) -> torch.Tensor:
    # Resize to multiples of patch size and normalize with ImageNet stats
    tensor_img = resize_transform(img, image_size=IMAGE_SIZE, patch_size=PATCH_SIZE)
    return normalize_image(tensor_img)


class FrameDataset(Dataset):
    def __init__(self, frames_df: pd.DataFrame, transform=frame_to_tensor):
        self.df = frames_df.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(row["frame_path"]).convert("RGB")
        tensor_img = self.transform(img)
        label = torch.tensor(row["label"], dtype=torch.float32)
        return tensor_img, label


class BalancedBatchSampler(Sampler):
    def __init__(self, zero_indices, one_indices, num_class0, num_class1, batches_per_epoch, seed=42):
        self.zero_indices = list(zero_indices)
        self.one_indices = list(one_indices)
        self.num_class0 = num_class0
        self.num_class1 = num_class1
        self.batches_per_epoch = batches_per_epoch
        self.seed = seed
        self.epoch = 0

    def __iter__(self):
        import numpy as np

        rng = np.random.default_rng(self.seed + self.epoch)
        for _ in range(self.batches_per_epoch):
            batch = []
            batch += rng.choice(
                self.zero_indices,
                size=self.num_class0,
                replace=len(self.zero_indices) < self.num_class0,
            ).tolist()
            batch += rng.choice(
                self.one_indices,
                size=self.num_class1,
                replace=len(self.one_indices) < self.num_class1,
            ).tolist()
            rng.shuffle(batch)
            yield batch
        self.epoch += 1

    def __len__(self):
        return self.batches_per_epoch


def make_balanced_train_loader(
    frames_df: pd.DataFrame,
    num_class0_per_batch: int,
    num_class1_per_batch: int,
    batches_per_epoch: int = 12,
    num_workers: int = 2,
):
    dataset = FrameDataset(frames_df)
    zero_indices = [i for i, lbl in enumerate(dataset.df["label"]) if lbl == 0]
    one_indices = [i for i, lbl in enumerate(dataset.df["label"]) if lbl == 1]
    if not zero_indices or not one_indices:
        raise ValueError("Both classes must be present to build a balanced loader.")

    batch_sampler = BalancedBatchSampler(
        zero_indices,
        one_indices,
        num_class0=num_class0_per_batch,
        num_class1=num_class1_per_batch,
        batches_per_epoch=batches_per_epoch,
    )

    return DataLoader(
        dataset,
        batch_sampler=batch_sampler,
        num_workers=num_workers,
        pin_memory=DEVICE != "cpu",
    )

from torch.utils.data import Subset

def make_eval_loader(
    frames_df: pd.DataFrame,
    batch_size: int = 1,
    num_workers: int = 2,
):
    dataset = FrameDataset(frames_df.reset_index(drop=True))
    eval_subset = Subset(dataset, list(range(min(1000, len(dataset)))))

    return DataLoader(
        eval_subset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=DEVICE != "cpu",
    )

In [11]:
import torch.nn as nn

# Infer feature dimension from the loaded DINO backbone
FEATURE_DIM = getattr(model, "num_features", getattr(model, "embed_dim", None))
if FEATURE_DIM is None:
    raise ValueError("Could not infer feature dimension from the DINO model.")

import torch
import torch.nn as nn

class AttnPool1D(nn.Module):
    """
    Learned attention pooling over a sequence of tokens.
    Uses a single learned query token to attend over patch tokens.
    """
    def __init__(self, dim: int, num_heads: int = 4):
        super().__init__()
        self.query = nn.Parameter(torch.randn(1, 1, dim))   # (1, 1, D)
        self.attn = nn.MultiheadAttention(
            embed_dim=dim,
            num_heads=num_heads,
            batch_first=True,
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        x: (B, N, D) patch tokens
        returns: (B, D) pooled feature
        """
        B, N, D = x.shape
        q = self.query.expand(B, -1, -1)    # (B, 1, D)
        pooled, _ = self.attn(q, x, x)      # (B, 1, D)
        return pooled.squeeze(1)            # (B, D)


class DinoDualPathBinaryClassifier(nn.Module):
    """
    - Frozen DINOv3 backbone
    - Path 1: deeper MLP on CLS token (global path)
    - Path 2: attention pooling over patch tokens + MLP (local path)
    - Final logit = cls_logit + patch_logit
    """
    def __init__(
        self,
        backbone,
        feature_dim: int,
        n_layers: int,
        layers=None,
        dropout: float = 0,
        patch_heads: int = 4,
    ):
        super().__init__()
        self.backbone = backbone
        self.layers = layers or [n_layers - 1]  # default: last layer

        # freeze DINO backbone
        for p in self.backbone.parameters():
            p.requires_grad = False

        # ---- CLS path: deeper MLP ----
        self.cls_head = nn.Sequential(
            nn.LayerNorm(feature_dim),
            nn.Linear(feature_dim, feature_dim),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(feature_dim, feature_dim // 2),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(feature_dim // 2, feature_dim // 4),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(feature_dim // 4, 1),   # scalar logit from CLS path
        )

        # ---- Patch path: attention pooling + MLP ----
        self.patch_pool = AttnPool1D(feature_dim, num_heads=patch_heads)

        self.patch_head = nn.Sequential(
            nn.LayerNorm(feature_dim),
            nn.Linear(feature_dim, feature_dim),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(feature_dim, feature_dim // 2),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(feature_dim // 2, feature_dim // 4),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(feature_dim // 4, 1),   # scalar logit from patch path
        )

    def forward(self, x: torch.Tensor):
        """
        x: (B, 3, H, W) preprocessed frames (already resized & normalized)
        """
        feats = self.backbone.get_intermediate_layers(
            x,
            n=self.layers,
            reshape=False,
            norm=True,
        )
        tokens = feats[-1]                 # (B, T, D) where T = 1 + extra + patches
        cls_tok = tokens[:, 0, :]         # (B, D)
        patch_tok = tokens[:, 1:, :]      # (B, T-1, D) (registers+patches, that's fine)

        # CLS path
        cls_logit = self.cls_head(cls_tok).squeeze(-1)        # (B,)

        # Patch path: attention pooling over tokens
        patch_pooled = self.patch_pool(patch_tok)             # (B, D)
        patch_logit = self.patch_head(patch_pooled).squeeze(-1)  # (B,)

        # Combine the two paths at the final node
        logit = cls_logit + patch_logit                       # (B,)

        return logit, cls_logit, patch_logit, cls_tok, patch_tok


def compute_metrics(targets, probs):
    preds = (probs >= 0.5).astype(int)
    acc = accuracy_score(targets, preds) if len(targets) else 0.0
    try:
        auc = roc_auc_score(targets, probs) if len(set(targets)) > 1 else float("nan")
    except ValueError:
        auc = float("nan")
    cm = confusion_matrix(targets, preds, labels=[0, 1]) if len(targets) else np.zeros((2, 2), dtype=int)
    return {"accuracy": acc, "auc": auc, "confusion_matrix": cm}


def run_epoch(loader, model, criterion, optimizer=None):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    running_loss = 0.0
    all_targets, all_probs = [], []

    iterable = tqdm.tqdm(loader, total=len(loader), desc="train" if is_train else "eval")

    for batch in iterable:
        imgs, labels = batch
        imgs = imgs.to(DEVICE)
        labels = labels.to(DEVICE)

        with torch.set_grad_enabled(is_train):
            logits, cls_logit, patch_logit, cls_tok, patch_tok = model(imgs)
            loss = criterion(logits, labels)

            if is_train:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

        running_loss += loss.item() * len(labels)
        probs = torch.sigmoid(logits).detach().cpu().numpy()
        all_probs.extend(probs.tolist())
        all_targets.extend(labels.detach().cpu().numpy().tolist())

    avg_loss = running_loss / max(1, len(loader.dataset))
    metrics = compute_metrics(np.array(all_targets), np.array(all_probs))
    metrics["loss"] = avg_loss
    return metrics

In [10]:
train_frames_df#[train_frames_df["label"]==1]

,video_name,frame_path,frame_index,time_seconds,label
0,01970,frames/images/01970_0.0s.jpg,0,0.0,0
1,01970,frames/images/01970_0.5s.jpg,15,0.5,0
2,01970,frames/images/01970_1.0s.jpg,30,1.0,0
3,01970,frames/images/01970_1.5s.jpg,45,1.5,0
4,01970,frames/images/01970_2.0s.jpg,60,2.0,0
...,...,...,...,...,...
70623,01720,frames/images/01720_38.0s.jpg,1140,38.0,0
70624,01720,frames/images/01720_38.5s.jpg,1155,38.5,0
70625,01720,frames/images/01720_39.0s.jpg,1170,39.0,0
70626,01720,frames/images/01720_39.5s.jpg,1185,39.5,0
70627,01720,frames/images/01720_40.0s.jpg,1200,40.0,0

In [16]:
# Example training/testing loop
train_loader = make_balanced_train_loader(
    train_frames_df,
    num_class0_per_batch=4,
    num_class1_per_batch=4,
    batches_per_epoch=10,
    num_workers=0,
)

test_loader = make_eval_loader(test_frames_df, batch_size=8, num_workers=0)

In [12]:

classifier = DinoDualPathBinaryClassifier(backbone=model, feature_dim=FEATURE_DIM, n_layers=N_LAYERS).to(DEVICE)
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(classifier.parameters(), lr=3e-4)

In [19]:
epochs = 1
for epoch in range(1, epochs + 1):
    train_stats = run_epoch(train_loader, classifier, criterion, optimizer)


    print(f"Epoch {epoch}/{epochs}")
    print("  Train -> loss: {loss:.4f}, acc: {accuracy:.3f}, auc: {auc}, cm:{confusion_matrix}".format(**train_stats))
    if epoch%100 == 0:
        test_stats = run_epoch(test_loader, classifier, criterion, optimizer=None)
        print("  Test  -> loss: {loss:.4f}, acc: {accuracy:.3f}, auc: {auc}, cm:{confusion_matrix}".format(**test_stats))

train:   0%|          | 0/10 [00:00<?, ?it/s]/Users/aneeshkalla/anaconda3/envs/driving/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
train: 100%|██████████| 10/10 [01:10<00:00,  7.06s/it]

Epoch 1/1
  Train -> loss: 0.0005, acc: 0.825, auc: 0.890625, cm:[[36  4]
 [10 30]]

In [ ]:
# Save model weights (and optionally optimizer state)
#v0: mlp with 2 layers on CLS token
#v1: mlp with 5 layers on both CLS and patch tokens, attn pooling on patch tokens
save_path = "dino_classifier_89auc_v1_12.4.3:24.pt"
torch.save(
    {
        "model_state": classifier.state_dict(),
        "optimizer_state": optimizer.state_dict(),
    },
    save_path,
)
print(f"Saved to {save_path}")

Saved to dino_classifier_89auc_v1_12.4.3:24.pt

# model evaluation

In [13]:
checkpoint = torch.load("dino_classifier_89auc_v1_12.4.3:24.pt", map_location=DEVICE)
classifier.load_state_dict(checkpoint["model_state"])
optimizer.load_state_dict(checkpoint["optimizer_state"])
classifier.to(DEVICE).eval()  # set eval as needed
print("Model and optimizer restored")

Model and optimizer restored

In [14]:
test_clips_df

,filepath,source,event_time,event_description,split,other_info
1116,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
1368,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
422,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,20.717,collision,train,"{""time_of_alert"": 18.833, ""light_conditions"": ..."
413,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,19.122,collision,train,"{""time_of_alert"": 18.162, ""light_conditions"": ..."
451,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,18.933,collision,train,"{""time_of_alert"": 18.033, ""light_conditions"": ..."
...,...,...,...,...,...,...
983,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
799,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
1265,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
1150,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."
824,hf://datasets/nexar-ai/nexar_collision_predict...,huggingface,NaN,no collision,train,"{""time_of_alert"": NaN, ""light_conditions"": ""No..."

### Collision threshold sweep

In [16]:
import numpy as np


def evaluate_clip_flags(
    row,
    model,
    thresholds,
    frame_interval_seconds=0.5,
    impact_window_seconds=2.0,
    batch_size=1,
):
    video_path = load_video(row)
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        delete_video(video_path)
        raise RuntimeError(f"Could not open video at {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    if not fps or fps <= 0:
        cap.release()
        delete_video(video_path)
        raise RuntimeError("Video FPS could not be determined")

    impact_time = float(row["event_time"]) if row["event_time"] is not None else None
    if impact_time is None or pd.isna(impact_time):
        cap.release()
        delete_video(video_path)
        return None  # skip clips without impact time
    
    print(impact_time)

    video_name = row.get("video_name", Path(video_path).stem)
    window_end = impact_time + float(impact_window_seconds)
    window_start = max(0.0, impact_time - float(impact_window_seconds))
    frame_step = max(1, int(round(frame_interval_seconds * fps)))

    frames, timestamps = [], []
    frame_idx = 0
    try:
        while True:
            success, frame = cap.read()
            if not success:
                break

            if frame_idx % frame_step != 0:
                frame_idx += 1
                continue

            timestamp = frame_idx / fps
            if timestamp > window_end:
                break  # stop evaluating beyond +impact_window_seconds

            img = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
            frames.append(frame_to_tensor(img))
            timestamps.append(timestamp)

            frame_idx += 1
    finally:
        cap.release()
        delete_video(video_path)

    if not frames:
        return {"video_name": video_name, "results": []}

    probs = []
    model.eval()
    with torch.no_grad():
        for i in range(0, len(frames), batch_size):
            batch = torch.stack(frames[i : i + batch_size]).to(DEVICE)
            logits, cls_logit, patch_logit, cls_tok, patch_tok = model(batch)
            probs.extend(torch.sigmoid(logits).cpu().numpy().tolist())

    clip_results = []
    for ts, prob in zip(timestamps, probs):
        in_window = window_start <= ts <= window_end
        clip_results.append((ts, prob, in_window))
    return {"video_name": video_name, "results": clip_results}


thresholds = np.arange(0.05, 1.0, 0.05)
stats = {
    t: {
        "clips_caught": 0,
        "clips_missed": 0,
        "misfire_frames": 0,
        "misfire_clips": set(),
    }
    for t in thresholds
}

clip_counter = 0
for _, clip_row in tqdm.tqdm(test_clips_df.iterrows(), total=len(test_clips_df), desc="threshold sweep"):
    clip_counter += 1
    clip_out = evaluate_clip_flags(clip_row, classifier, thresholds)
    if not clip_out or not clip_out["results"]:
        continue

    video_name = clip_out["video_name"]
    clip_preds = clip_out["results"]

    caught_clip_flags = {t: False for t in thresholds}
    misfire_clip_flags = {t: False for t in thresholds}
    misfire_frame_counts = {t: 0 for t in thresholds}

    for ts, prob, in_window in clip_preds:
        for t in thresholds:
            pred = prob >= t
            if pred:
                if in_window:
                    caught_clip_flags[t] = True
                else:
                    misfire_frame_counts[t] += 1
                    misfire_clip_flags[t] = True

    for t in thresholds:
        if caught_clip_flags[t]:
            stats[t]["clips_caught"] += 1
        else:
            stats[t]["clips_missed"] += 1

        stats[t]["misfire_frames"] += misfire_frame_counts[t]
        if misfire_clip_flags[t]:
            stats[t]["misfire_clips"].add(video_name)

    if clip_counter % 1 == 0:
        print(f"Processed {clip_counter} clips...")
        temp_results = []
        for t in thresholds:
            entry = stats[t].copy()
            entry["threshold"] = round(float(t), 2)
            entry["misfire_clips"] = len(entry["misfire_clips"])
            temp_results.append(entry)
        temp_df = pd.DataFrame(temp_results).sort_values("threshold")
        display(temp_df)

results = []
for t in thresholds:
    entry = stats[t].copy()
    entry["threshold"] = round(float(t), 2)
    entry["misfire_clips"] = len(entry["misfire_clips"])
    results.append(entry)

threshold_results_df = pd.DataFrame(results).sort_values("threshold")
threshold_results_df

threshold sweep:   0%|          | 0/300 [00:00<?, ?it/s]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01910.mp4 from Hugging Face...

threshold sweep:   0%|          | 1/300 [00:00<02:24,  2.07it/s]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01910.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01401.mp4 from Hugging Face...

threshold sweep:   1%|          | 2/300 [00:00<01:44,  2.85it/s]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01401.mp4
20.717
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00407.mp4
Processed 3 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0              1             0              38              1       0.05
1              1             0              38              1       0.10
2              1             0              38              1       0.15
3              1             0              36              1       0.20
4              1             0              33              1       0.25
5              1             0              26              1       0.30
6              1             0              23              1       0.35
7              1             0              20              1       0.40
8              1             0              17              1       0.45
9              1             0              13              1       0.50
10             1             0              10              1       0.55
11             1             0               7              1       0.60
12             1             0               6              1       0.65
13             1             0               4              1       0.70
14             1             0               1              1       0.75
15             1             0               0              0       0.80
16             1             0               0              0       0.85
17             1             0               0              0       0.90
18             0             1               0              0       0.95

threshold sweep:   1%|          | 3/300 [00:39<1:28:33, 17.89s/it]

19.122
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00911.mp4
Processed 4 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0              2             0              72              2       0.05
1              2             0              72              2       0.10
2              2             0              72              2       0.15
3              2             0              70              2       0.20
4              2             0              67              2       0.25
5              2             0              60              2       0.30
6              2             0              57              2       0.35
7              2             0              54              2       0.40
8              2             0              49              2       0.45
9              2             0              21              2       0.50
10             2             0              14              2       0.55
11             2             0               9              2       0.60
12             2             0               7              2       0.65
13             2             0               4              1       0.70
14             2             0               1              1       0.75
15             2             0               0              0       0.80
16             2             0               0              0       0.85
17             2             0               0              0       0.90
18             0             2               0              0       0.95

threshold sweep:   1%|▏         | 4/300 [01:13<1:59:47, 24.28s/it]

18.933
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00906.mp4
Processed 5 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0              3             0             106              3       0.05
1              3             0             106              3       0.10
2              3             0              91              3       0.15
3              3             0              82              3       0.20
4              3             0              76              3       0.25
5              3             0              69              3       0.30
6              3             0              65              3       0.35
7              3             0              61              3       0.40
8              3             0              55              3       0.45
9              3             0              24              3       0.50
10             3             0              15              3       0.55
11             3             0               9              2       0.60
12             3             0               7              2       0.65
13             3             0               4              1       0.70
14             3             0               1              1       0.75
15             3             0               0              0       0.80
16             3             0               0              0       0.85
17             3             0               0              0       0.90
18             0             3               0              0       0.95

threshold sweep:   2%|▏         | 5/300 [01:48<2:18:58, 28.27s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01812.mp4 from Hugging Face...

threshold sweep:   2%|▏         | 6/300 [01:49<1:32:17, 18.84s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01812.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01660.mp4 from Hugging Face...

threshold sweep:   2%|▏         | 7/300 [01:49<1:02:27, 12.79s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01660.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00523.mp4 from Hugging Face...
20.3
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00523.mp4
Processed 8 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0              4             0             143              4       0.05
1              4             0             143              4       0.10
2              4             0             128              4       0.15
3              4             0             119              4       0.20
4              4             0             108              4       0.25
5              4             0              91              4       0.30
6              4             0              85              4       0.35
7              4             0              78              4       0.40
8              4             0              70              4       0.45
9              4             0              38              4       0.50
10             4             0              24              4       0.55
11             3             1              18              3       0.60
12             3             1              14              3       0.65
13             3             1              10              2       0.70
14             3             1               1              1       0.75
15             3             1               0              0       0.80
16             3             1               0              0       0.85
17             3             1               0              0       0.90
18             0             4               0              0       0.95

threshold sweep:   3%|▎         | 8/300 [02:28<1:41:38, 20.88s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01503.mp4 from Hugging Face...

threshold sweep:   3%|▎         | 9/300 [02:28<1:10:27, 14.53s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01503.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00664.mp4 from Hugging Face...
20.833
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00664.mp4
Processed 10 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0              5             0             181              5       0.05
1              5             0             181              5       0.10
2              5             0             158              5       0.15
3              5             0             121              5       0.20
4              5             0             109              5       0.25
5              5             0              92              5       0.30
6              5             0              85              4       0.35
7              5             0              78              4       0.40
8              5             0              70              4       0.45
9              5             0              38              4       0.50
10             5             0              24              4       0.55
11             3             2              18              3       0.60
12             3             2              14              3       0.65
13             3             2              10              2       0.70
14             3             2               1              1       0.75
15             3             2               0              0       0.80
16             3             2               0              0       0.85
17             3             2               0              0       0.90
18             0             5               0              0       0.95

threshold sweep:   3%|▎         | 10/300 [03:07<1:46:12, 21.98s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01839.mp4 from Hugging Face...

threshold sweep:   4%|▎         | 11/300 [03:07<1:14:02, 15.37s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01839.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01498.mp4 from Hugging Face...

threshold sweep:   4%|▍         | 12/300 [03:08<52:09, 10.87s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01498.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00062.mp4 from Hugging Face...
18.867
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00062.mp4
Processed 13 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0              6             0             215              6       0.05
1              6             0             215              6       0.10
2              6             0             192              6       0.15
3              6             0             152              6       0.20
4              6             0             131              6       0.25
5              5             1             108              6       0.30
6              5             1              97              5       0.35
7              5             1              90              5       0.40
8              5             1              78              5       0.45
9              5             1              46              5       0.50
10             5             1              29              5       0.55
11             3             3              23              4       0.60
12             3             3              17              4       0.65
13             3             3              12              3       0.70
14             3             3               1              1       0.75
15             3             3               0              0       0.80
16             3             3               0              0       0.85
17             3             3               0              0       0.90
18             0             6               0              0       0.95

threshold sweep:   4%|▍         | 13/300 [03:43<1:27:58, 18.39s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01248.mp4 from Hugging Face...

threshold sweep:   5%|▍         | 14/300 [03:44<1:02:24, 13.09s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01248.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00861.mp4 from Hugging Face...
20.9
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00861.mp4
Processed 15 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0              7             0             253              7       0.05
1              7             0             253              7       0.10
2              7             0             222              7       0.15
3              7             0             157              7       0.20
4              7             0             134              7       0.25
5              6             1             111              7       0.30
6              6             1             100              6       0.35
7              6             1              92              6       0.40
8              6             1              80              6       0.45
9              6             1              48              6       0.50
10             6             1              31              6       0.55
11             4             3              25              5       0.60
12             4             3              19              5       0.65
13             4             3              14              4       0.70
14             4             3               2              2       0.75
15             4             3               0              0       0.80
16             4             3               0              0       0.85
17             4             3               0              0       0.90
18             0             7               0              0       0.95

threshold sweep:   5%|▌         | 15/300 [04:24<1:40:47, 21.22s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01288.mp4 from Hugging Face...

threshold sweep:   5%|▌         | 16/300 [04:25<1:10:49, 14.96s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01288.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01872.mp4 from Hugging Face...

threshold sweep:   6%|▌         | 17/300 [04:25<49:59, 10.60s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01872.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00464.mp4 from Hugging Face...
19.733
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00464.mp4
Processed 18 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0              8             0             289              8       0.05
1              8             0             289              8       0.10
2              8             0             258              8       0.15
3              8             0             188              8       0.20
4              8             0             150              8       0.25
5              7             1             121              8       0.30
6              7             1             107              7       0.35
7              7             1              96              7       0.40
8              7             1              82              7       0.45
9              7             1              49              7       0.50
10             7             1              32              7       0.55
11             5             3              25              5       0.60
12             5             3              19              5       0.65
13             5             3              14              4       0.70
14             5             3               2              2       0.75
15             5             3               0              0       0.80
16             5             3               0              0       0.85
17             5             3               0              0       0.90
18             0             8               0              0       0.95

threshold sweep:   6%|▌         | 18/300 [05:02<1:27:33, 18.63s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00818.mp4 from Hugging Face...
19.133
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00818.mp4
Processed 19 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0              9             0             324              9       0.05
1              9             0             324              9       0.10
2              9             0             293              9       0.15
3              9             0             223              9       0.20
4              9             0             163              9       0.25
5              8             1             126              9       0.30
6              8             1             110              8       0.35
7              8             1              99              8       0.40
8              8             1              85              8       0.45
9              8             1              51              8       0.50
10             8             1              34              8       0.55
11             6             3              26              6       0.60
12             6             3              19              5       0.65
13             6             3              14              4       0.70
14             6             3               2              2       0.75
15             6             3               0              0       0.80
16             5             4               0              0       0.85
17             5             4               0              0       0.90
18             0             9               0              0       0.95

threshold sweep:   6%|▋         | 19/300 [05:39<1:52:01, 23.92s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00058.mp4 from Hugging Face...
19.149
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00058.mp4
Processed 20 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             10             0             359             10       0.05
1             10             0             359             10       0.10
2             10             0             328             10       0.15
3             10             0             258             10       0.20
4             10             0             198             10       0.25
5              9             1             161             10       0.30
6              9             1             145              9       0.35
7              9             1             134              9       0.40
8              9             1             120              9       0.45
9              9             1              86              9       0.50
10             9             1              69              9       0.55
11             7             3              61              7       0.60
12             7             3              54              6       0.65
13             7             3              49              5       0.70
14             7             3              37              3       0.75
15             7             3              29              1       0.80
16             6             4              16              1       0.85
17             6             4               1              1       0.90
18             0            10               0              0       0.95

threshold sweep:   7%|▋         | 20/300 [06:16<2:10:09, 27.89s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/02080.mp4 from Hugging Face...

threshold sweep:   7%|▋         | 21/300 [06:16<1:31:22, 19.65s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/02080.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01822.mp4 from Hugging Face...

threshold sweep:   7%|▋         | 22/300 [06:17<1:04:20, 13.89s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01822.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/02119.mp4 from Hugging Face...

threshold sweep:   8%|▊         | 23/300 [06:17<45:27,  9.85s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/02119.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01453.mp4 from Hugging Face...

threshold sweep:   8%|▊         | 24/300 [06:18<32:14,  7.01s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01453.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/02090.mp4 from Hugging Face...

threshold sweep:   8%|▊         | 25/300 [06:18<23:00,  5.02s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/02090.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00345.mp4 from Hugging Face...
19.467
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00345.mp4
Processed 26 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             11             0             394             11       0.05
1             11             0             394             11       0.10
2             11             0             348             11       0.15
3             11             0             261             11       0.20
4             11             0             199             11       0.25
5             10             1             161             10       0.30
6             10             1             145              9       0.35
7             10             1             134              9       0.40
8             10             1             120              9       0.45
9             10             1              86              9       0.50
10            10             1              69              9       0.55
11             8             3              61              7       0.60
12             8             3              54              6       0.65
13             8             3              49              5       0.70
14             8             3              37              3       0.75
15             8             3              29              1       0.80
16             7             4              16              1       0.85
17             7             4               1              1       0.90
18             0            11               0              0       0.95

threshold sweep:   9%|▊         | 26/300 [06:55<1:06:28, 14.55s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01459.mp4 from Hugging Face...

threshold sweep:   9%|▉         | 27/300 [06:55<46:50, 10.29s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01459.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01946.mp4 from Hugging Face...

threshold sweep:   9%|▉         | 28/300 [06:55<33:00,  7.28s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01946.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/02054.mp4 from Hugging Face...

threshold sweep:  10%|▉         | 29/300 [06:56<23:21,  5.17s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/02054.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/02136.mp4 from Hugging Face...

threshold sweep:  10%|█         | 30/300 [06:56<16:43,  3.72s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/02136.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/02072.mp4 from Hugging Face...

threshold sweep:  10%|█         | 31/300 [06:56<11:57,  2.67s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/02072.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00485.mp4 from Hugging Face...
19.2
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00485.mp4
Processed 32 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             12             0             429             12       0.05
1             12             0             429             12       0.10
2             12             0             383             12       0.15
3             12             0             296             12       0.20
4             12             0             234             12       0.25
5             11             1             194             11       0.30
6             11             1             170             10       0.35
7             11             1             147             10       0.40
8             11             1             127             10       0.45
9             11             1              89             10       0.50
10            11             1              71             10       0.55
11             9             3              62              8       0.60
12             9             3              54              6       0.65
13             9             3              49              5       0.70
14             9             3              37              3       0.75
15             9             3              29              1       0.80
16             8             4              16              1       0.85
17             8             4               1              1       0.90
18             0            12               0              0       0.95

threshold sweep:  11%|█         | 32/300 [07:33<57:10, 12.80s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01417.mp4 from Hugging Face...

threshold sweep:  11%|█         | 33/300 [07:33<40:34,  9.12s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01417.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01211.mp4 from Hugging Face...

threshold sweep:  11%|█▏        | 34/300 [07:33<28:45,  6.49s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01211.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00167.mp4 from Hugging Face...
20.0
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00167.mp4
Processed 35 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             13             0             465             13       0.05
1             13             0             465             13       0.10
2             13             0             419             13       0.15
3             13             0             332             13       0.20
4             13             0             270             13       0.25
5             12             1             230             12       0.30
6             12             1             206             11       0.35
7             12             1             183             11       0.40
8             12             1             162             11       0.45
9             12             1             123             11       0.50
10            12             1             103             11       0.55
11            10             3              92              9       0.60
12            10             3              81              7       0.65
13            10             3              71              6       0.70
14            10             3              56              4       0.75
15            10             3              40              2       0.80
16             9             4              24              2       0.85
17             8             5               3              2       0.90
18             0            13               0              0       0.95

threshold sweep:  12%|█▏        | 35/300 [08:11<1:10:23, 15.94s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00254.mp4 from Hugging Face...
18.533
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00254.mp4
Processed 36 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             14             0             499             14       0.05
1             14             0             499             14       0.10
2             14             0             453             14       0.15
3             14             0             366             14       0.20
4             14             0             299             14       0.25
5             13             1             242             13       0.30
6             13             1             214             12       0.35
7             13             1             190             12       0.40
8             13             1             169             12       0.45
9             13             1             130             12       0.50
10            13             1             108             12       0.55
11            11             3              97             10       0.60
12            11             3              84              8       0.65
13            11             3              74              7       0.70
14            11             3              58              5       0.75
15            11             3              41              3       0.80
16            10             4              24              2       0.85
17             8             6               3              2       0.90
18             0            14               0              0       0.95

threshold sweep:  12%|█▏        | 36/300 [08:47<1:35:56, 21.80s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00966.mp4 from Hugging Face...
19.728
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00966.mp4
Processed 37 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             15             0             534             15       0.05
1             15             0             534             15       0.10
2             15             0             488             15       0.15
3             15             0             401             15       0.20
4             15             0             334             15       0.25
5             14             1             277             14       0.30
6             14             1             249             13       0.35
7             14             1             225             13       0.40
8             14             1             204             13       0.45
9             14             1             163             13       0.50
10            14             1             140             13       0.55
11            12             3             122             11       0.60
12            12             3             102              9       0.65
13            12             3              89              8       0.70
14            12             3              65              6       0.75
15            12             3              47              4       0.80
16            11             4              25              3       0.85
17             9             6               4              3       0.90
18             0            15               0              0       0.95

threshold sweep:  12%|█▏        | 37/300 [09:23<1:54:34, 26.14s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00895.mp4 from Hugging Face...
20.586
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00895.mp4
Processed 38 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             16             0             572             16       0.05
1             16             0             572             16       0.10
2             16             0             526             16       0.15
3             16             0             439             16       0.20
4             16             0             372             16       0.25
5             15             1             315             15       0.30
6             15             1             275             14       0.35
7             15             1             241             14       0.40
8             15             1             211             14       0.45
9             15             1             166             14       0.50
10            15             1             141             14       0.55
11            13             3             122             11       0.60
12            13             3             102              9       0.65
13            13             3              89              8       0.70
14            13             3              65              6       0.75
15            13             3              47              4       0.80
16            12             4              25              3       0.85
17             9             7               4              3       0.90
18             0            16               0              0       0.95

threshold sweep:  13%|█▎        | 38/300 [10:02<2:10:53, 29.98s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01805.mp4 from Hugging Face...

threshold sweep:  13%|█▎        | 39/300 [10:02<1:31:45, 21.09s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01805.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00437.mp4 from Hugging Face...
20.167
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00437.mp4
Processed 40 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             17             0             609             17       0.05
1             17             0             609             17       0.10
2             17             0             563             17       0.15
3             17             0             475             17       0.20
4             17             0             399             17       0.25
5             16             1             335             16       0.30
6             16             1             283             15       0.35
7             16             1             246             15       0.40
8             16             1             215             15       0.45
9             16             1             168             15       0.50
10            16             1             142             15       0.55
11            14             3             123             12       0.60
12            14             3             103             10       0.65
13            14             3              89              8       0.70
14            14             3              65              6       0.75
15            14             3              47              4       0.80
16            13             4              25              3       0.85
17            10             7               4              3       0.90
18             0            17               0              0       0.95

threshold sweep:  13%|█▎        | 40/300 [10:41<1:53:29, 26.19s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01301.mp4 from Hugging Face...

threshold sweep:  14%|█▎        | 41/300 [10:41<1:19:37, 18.45s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01301.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00915.mp4 from Hugging Face...
10.659
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00915.mp4
Processed 42 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             18             0             627             18       0.05
1             18             0             627             18       0.10
2             18             0             581             18       0.15
3             18             0             475             17       0.20
4             18             0             399             17       0.25
5             17             1             335             16       0.30
6             17             1             283             15       0.35
7             17             1             246             15       0.40
8             17             1             215             15       0.45
9             17             1             168             15       0.50
10            17             1             142             15       0.55
11            15             3             123             12       0.60
12            15             3             103             10       0.65
13            15             3              89              8       0.70
14            15             3              65              6       0.75
15            15             3              47              4       0.80
16            14             4              25              3       0.85
17            10             8               4              3       0.90
18             0            18               0              0       0.95

threshold sweep:  14%|█▍        | 42/300 [11:03<1:23:51, 19.50s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01968.mp4 from Hugging Face...

threshold sweep:  14%|█▍        | 43/300 [11:03<58:47, 13.72s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01968.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01526.mp4 from Hugging Face...

threshold sweep:  15%|█▍        | 44/300 [11:03<41:22,  9.70s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01526.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01768.mp4 from Hugging Face...

threshold sweep:  15%|█▌        | 45/300 [11:04<29:10,  6.86s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01768.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00644.mp4 from Hugging Face...
20.909
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00644.mp4
Processed 46 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             19             0             666             19       0.05
1             19             0             666             19       0.10
2             19             0             620             19       0.15
3             19             0             514             18       0.20
4             19             0             438             18       0.25
5             18             1             374             17       0.30
6             18             1             322             16       0.35
7             18             1             280             16       0.40
8             18             1             243             16       0.45
9             18             1             191             16       0.50
10            18             1             161             16       0.55
11            16             3             141             13       0.60
12            16             3             121             11       0.65
13            16             3             105              9       0.70
14            16             3              75              7       0.75
15            16             3              51              5       0.80
16            15             4              25              3       0.85
17            11             8               4              3       0.90
18             0            19               0              0       0.95

threshold sweep:  15%|█▌        | 46/300 [11:42<1:09:06, 16.32s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00194.mp4 from Hugging Face...
20.329
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00194.mp4
Processed 47 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             20             0             704             20       0.05
1             20             0             704             20       0.10
2             20             0             658             20       0.15
3             20             0             546             19       0.20
4             20             0             459             19       0.25
5             19             1             385             18       0.30
6             19             1             330             17       0.35
7             19             1             288             17       0.40
8             19             1             249             17       0.45
9             19             1             195             17       0.50
10            19             1             162             17       0.55
11            17             3             141             13       0.60
12            17             3             121             11       0.65
13            17             3             105              9       0.70
14            17             3              75              7       0.75
15            17             3              51              5       0.80
16            16             4              25              3       0.85
17            12             8               4              3       0.90
18             0            20               0              0       0.95

threshold sweep:  16%|█▌        | 47/300 [12:20<1:36:40, 22.93s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00064.mp4 from Hugging Face...
8.167
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00064.mp4
Processed 48 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             21             0             717             21       0.05
1             21             0             717             21       0.10
2             21             0             671             21       0.15
3             21             0             550             20       0.20
4             21             0             460             20       0.25
5             20             1             385             18       0.30
6             20             1             330             17       0.35
7             20             1             288             17       0.40
8             20             1             249             17       0.45
9             20             1             195             17       0.50
10            20             1             162             17       0.55
11            18             3             141             13       0.60
12            18             3             121             11       0.65
13            18             3             105              9       0.70
14            17             4              75              7       0.75
15            17             4              51              5       0.80
16            16             5              25              3       0.85
17            12             9               4              3       0.90
18             0            21               0              0       0.95

threshold sweep:  16%|█▌        | 48/300 [12:38<1:29:18, 21.27s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00242.mp4 from Hugging Face...
20.567
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00242.mp4
Processed 49 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             22             0             755             22       0.05
1             22             0             755             22       0.10
2             22             0             709             22       0.15
3             22             0             580             21       0.20
4             22             0             482             21       0.25
5             21             1             402             19       0.30
6             21             1             346             18       0.35
7             21             1             301             18       0.40
8             21             1             261             18       0.45
9             21             1             205             18       0.50
10            21             1             170             18       0.55
11            19             3             146             14       0.60
12            19             3             126             12       0.65
13            19             3             110             10       0.70
14            18             4              79              8       0.75
15            17             5              54              6       0.80
16            16             6              26              4       0.85
17            12            10               4              3       0.90
18             0            22               0              0       0.95

threshold sweep:  16%|█▋        | 49/300 [13:15<1:48:42, 25.99s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01393.mp4 from Hugging Face...

threshold sweep:  17%|█▋        | 50/300 [13:15<1:16:35, 18.38s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01393.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00647.mp4 from Hugging Face...
19.5
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00647.mp4
Processed 51 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             23             0             790             23       0.05
1             23             0             790             23       0.10
2             23             0             744             23       0.15
3             23             0             615             22       0.20
4             23             0             512             22       0.25
5             22             1             432             20       0.30
6             22             1             374             19       0.35
7             22             1             325             19       0.40
8             22             1             279             19       0.45
9             22             1             220             19       0.50
10            22             1             184             19       0.55
11            20             3             158             15       0.60
12            20             3             137             13       0.65
13            20             3             120             11       0.70
14            18             5              86              9       0.75
15            17             6              57              7       0.80
16            16             7              29              5       0.85
17            12            11               4              3       0.90
18             0            23               0              0       0.95

threshold sweep:  17%|█▋        | 51/300 [13:52<1:38:38, 23.77s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00296.mp4 from Hugging Face...
19.5
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00296.mp4
Processed 52 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             24             0             825             24       0.05
1             24             0             825             24       0.10
2             24             0             779             24       0.15
3             24             0             650             23       0.20
4             24             0             547             23       0.25
5             23             1             466             21       0.30
6             23             1             405             20       0.35
7             23             1             353             20       0.40
8             23             1             306             20       0.45
9             23             1             247             20       0.50
10            23             1             208             20       0.55
11            21             3             177             16       0.60
12            21             3             154             14       0.65
13            21             3             135             12       0.70
14            19             5              99             10       0.75
15            18             6              66              8       0.80
16            17             7              31              6       0.85
17            13            11               4              3       0.90
18             0            24               0              0       0.95

threshold sweep:  17%|█▋        | 52/300 [14:27<1:52:55, 27.32s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01109.mp4 from Hugging Face...

threshold sweep:  18%|█▊        | 53/300 [14:28<1:19:31, 19.32s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01109.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01612.mp4 from Hugging Face...

threshold sweep:  18%|█▊        | 54/300 [14:28<55:44, 13.60s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01612.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00634.mp4 from Hugging Face...
19.9
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00634.mp4
Processed 55 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             25             0             861             25       0.05
1             25             0             861             25       0.10
2             25             0             812             25       0.15
3             25             0             665             24       0.20
4             25             0             557             24       0.25
5             24             1             474             22       0.30
6             24             1             408             21       0.35
7             24             1             354             21       0.40
8             24             1             307             21       0.45
9             23             2             247             20       0.50
10            23             2             208             20       0.55
11            21             4             177             16       0.60
12            21             4             154             14       0.65
13            21             4             135             12       0.70
14            19             6              99             10       0.75
15            18             7              66              8       0.80
16            17             8              31              6       0.85
17            13            12               4              3       0.90
18             0            25               0              0       0.95

threshold sweep:  18%|█▊        | 55/300 [15:04<1:22:16, 20.15s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00896.mp4 from Hugging Face...
19.6
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00896.mp4
Processed 56 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             26             0             897             26       0.05
1             26             0             897             26       0.10
2             26             0             848             26       0.15
3             26             0             701             25       0.20
4             26             0             592             25       0.25
5             25             1             503             23       0.30
6             25             1             427             22       0.35
7             25             1             365             22       0.40
8             25             1             312             22       0.45
9             24             2             249             21       0.50
10            24             2             209             21       0.55
11            22             4             177             16       0.60
12            22             4             154             14       0.65
13            22             4             135             12       0.70
14            20             6              99             10       0.75
15            19             7              66              8       0.80
16            17             9              31              6       0.85
17            13            13               4              3       0.90
18             0            26               0              0       0.95

threshold sweep:  19%|█▊        | 56/300 [15:40<1:42:00, 25.08s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00473.mp4 from Hugging Face...
21.067
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00473.mp4
Processed 57 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             27             0             936             27       0.05
1             27             0             936             27       0.10
2             27             0             879             27       0.15
3             27             0             707             26       0.20
4             27             0             595             26       0.25
5             26             1             503             23       0.30
6             26             1             427             22       0.35
7             26             1             365             22       0.40
8             26             1             312             22       0.45
9             25             2             249             21       0.50
10            25             2             209             21       0.55
11            23             4             177             16       0.60
12            23             4             154             14       0.65
13            23             4             135             12       0.70
14            21             6              99             10       0.75
15            20             7              66              8       0.80
16            18             9              31              6       0.85
17            14            13               4              3       0.90
18             0            27               0              0       0.95

threshold sweep:  19%|█▉        | 57/300 [16:19<1:57:29, 29.01s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00458.mp4 from Hugging Face...
19.067
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00458.mp4
Processed 58 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             28             0             971             28       0.05
1             28             0             971             28       0.10
2             28             0             914             28       0.15
3             28             0             742             27       0.20
4             28             0             630             27       0.25
5             27             1             538             24       0.30
6             27             1             460             23       0.35
7             27             1             392             23       0.40
8             27             1             332             23       0.45
9             26             2             265             22       0.50
10            26             2             222             22       0.55
11            24             4             179             17       0.60
12            24             4             154             14       0.65
13            24             4             135             12       0.70
14            22             6              99             10       0.75
15            21             7              66              8       0.80
16            19             9              31              6       0.85
17            15            13               4              3       0.90
18             0            28               0              0       0.95

threshold sweep:  19%|█▉        | 58/300 [16:54<2:04:33, 30.88s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00467.mp4 from Hugging Face...
19.6
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00467.mp4
Processed 59 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             29             0            1007             29       0.05
1             29             0            1007             29       0.10
2             29             0             950             29       0.15
3             29             0             778             28       0.20
4             29             0             666             28       0.25
5             28             1             574             25       0.30
6             28             1             496             24       0.35
7             28             1             428             24       0.40
8             28             1             368             24       0.45
9             27             2             301             23       0.50
10            27             2             258             23       0.55
11            25             4             215             18       0.60
12            25             4             190             15       0.65
13            25             4             171             13       0.70
14            23             6             135             11       0.75
15            22             7             101              9       0.80
16            20             9              57              7       0.85
17            16            13               6              4       0.90
18             0            29               0              0       0.95

threshold sweep:  20%|█▉        | 59/300 [17:29<2:09:36, 32.27s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01281.mp4 from Hugging Face...

threshold sweep:  20%|██        | 60/300 [17:30<1:30:53, 22.72s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01281.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00804.mp4 from Hugging Face...
18.733
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00804.mp4
Processed 61 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             30             0            1041             30       0.05
1             30             0            1041             30       0.10
2             30             0             984             30       0.15
3             30             0             804             29       0.20
4             30             0             683             29       0.25
5             29             1             584             26       0.30
6             29             1             501             25       0.35
7             29             1             433             25       0.40
8             29             1             372             25       0.45
9             28             2             304             24       0.50
10            28             2             260             24       0.55
11            26             4             216             19       0.60
12            26             4             191             16       0.65
13            26             4             172             14       0.70
14            24             6             136             12       0.75
15            23             7             102             10       0.80
16            21             9              57              7       0.85
17            17            13               6              4       0.90
18             0            30               0              0       0.95

threshold sweep:  20%|██        | 61/300 [18:02<1:42:21, 25.70s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00652.mp4 from Hugging Face...
18.967
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00652.mp4
Processed 62 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             31             0            1075             31       0.05
1             31             0            1075             31       0.10
2             31             0            1018             31       0.15
3             31             0             838             30       0.20
4             31             0             717             30       0.25
5             30             1             618             27       0.30
6             30             1             535             26       0.35
7             30             1             467             26       0.40
8             30             1             406             26       0.45
9             29             2             338             25       0.50
10            29             2             294             25       0.55
11            27             4             250             20       0.60
12            27             4             224             17       0.65
13            27             4             204             15       0.70
14            25             6             159             13       0.75
15            24             7             116             11       0.80
16            22             9              58              8       0.85
17            18            13               6              4       0.90
18             0            31               0              0       0.95

threshold sweep:  21%|██        | 62/300 [18:35<1:50:34, 27.88s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00627.mp4 from Hugging Face...
20.333
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00627.mp4
Processed 63 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             32             0            1112             32       0.05
1             32             0            1112             32       0.10
2             32             0            1055             32       0.15
3             32             0             872             31       0.20
4             32             0             737             31       0.25
5             31             1             627             28       0.30
6             31             1             544             27       0.35
7             31             1             476             27       0.40
8             31             1             414             27       0.45
9             30             2             345             26       0.50
10            30             2             300             26       0.55
11            28             4             254             21       0.60
12            28             4             227             18       0.65
13            28             4             205             16       0.70
14            26             6             160             14       0.75
15            25             7             117             12       0.80
16            23             9              58              8       0.85
17            18            14               6              4       0.90
18             0            32               0              0       0.95

threshold sweep:  21%|██        | 63/300 [19:11<1:58:58, 30.12s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00705.mp4 from Hugging Face...
21.86
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00705.mp4
Processed 64 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             33             0            1153             33       0.05
1             33             0            1153             33       0.10
2             33             0            1096             33       0.15
3             33             0             913             32       0.20
4             33             0             778             32       0.25
5             32             1             668             29       0.30
6             32             1             585             28       0.35
7             32             1             515             28       0.40
8             32             1             451             28       0.45
9             31             2             375             27       0.50
10            31             2             320             27       0.55
11            29             4             268             22       0.60
12            29             4             234             19       0.65
13            29             4             207             17       0.70
14            27             6             161             15       0.75
15            26             7             117             12       0.80
16            23            10              58              8       0.85
17            18            15               6              4       0.90
18             0            33               0              0       0.95

threshold sweep:  21%|██▏       | 64/300 [19:49<2:07:39, 32.46s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01714.mp4 from Hugging Face...

threshold sweep:  22%|██▏       | 65/300 [19:49<1:29:41, 22.90s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01714.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00859.mp4 from Hugging Face...
19.892
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00859.mp4
Processed 66 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             34             0            1190             34       0.05
1             34             0            1190             34       0.10
2             34             0            1133             34       0.15
3             34             0             948             33       0.20
4             34             0             809             33       0.25
5             33             1             698             30       0.30
6             33             1             614             29       0.35
7             33             1             543             29       0.40
8             33             1             478             29       0.45
9             32             2             402             28       0.50
10            32             2             347             28       0.55
11            30             4             294             23       0.60
12            30             4             260             20       0.65
13            30             4             232             18       0.70
14            28             6             186             16       0.75
15            27             7             124             13       0.80
16            24            10              58              8       0.85
17            19            15               6              4       0.90
18             0            34               0              0       0.95

threshold sweep:  22%|██▏       | 66/300 [20:24<1:43:21, 26.50s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00488.mp4 from Hugging Face...
23.6
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00488.mp4
Processed 67 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             35             0            1234             35       0.05
1             35             0            1234             35       0.10
2             35             0            1177             35       0.15
3             35             0             992             34       0.20
4             35             0             849             34       0.25
5             34             1             734             31       0.30
6             34             1             649             30       0.35
7             34             1             575             30       0.40
8             34             1             508             30       0.45
9             33             2             431             29       0.50
10            33             2             374             29       0.55
11            31             4             320             24       0.60
12            31             4             284             21       0.65
13            31             4             255             19       0.70
14            29             6             189             17       0.75
15            28             7             126             14       0.80
16            25            10              59              9       0.85
17            20            15               6              4       0.90
18             0            35               0              0       0.95

threshold sweep:  22%|██▏       | 67/300 [21:06<2:00:23, 31.00s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01683.mp4 from Hugging Face...

threshold sweep:  23%|██▎       | 68/300 [21:06<1:24:22, 21.82s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01683.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/negative/01586.mp4 from Hugging Face...

threshold sweep:  23%|██▎       | 69/300 [21:06<59:10, 15.37s/it]

Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/01586.mp4
Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00209.mp4 from Hugging Face...
18.533
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00209.mp4
Processed 70 clips...

    clips_caught  clips_missed  misfire_frames  misfire_clips  threshold
0             36             0            1268             36       0.05
1             36             0            1268             36       0.10
2             36             0            1211             36       0.15
3             36             0            1026             35       0.20
4             36             0             883             35       0.25
5             35             1             767             32       0.30
6             35             1             680             31       0.35
7             35             1             601             31       0.40
8             35             1             527             31       0.45
9             34             2             435             30       0.50
10            34             2             374             29       0.55
11            31             5             320             24       0.60
12            31             5             284             21       0.65
13            31             5             255             19       0.70
14            29             7             189             17       0.75
15            28             8             126             14       0.80
16            25            11              59              9       0.85
17            20            16               6              4       0.90
18             0            36               0              0       0.95

threshold sweep:  23%|██▎       | 70/300 [21:42<1:22:01, 21.40s/it]

Downloading hf://datasets/nexar-ai/nexar_collision_prediction@eb317f47450998080aa5c5ff552824481128db65/train/positive/00324.mp4 from Hugging Face...
20.05
Deleted: /Users/aneeshkalla/Desktop/Driving_Tool/temp_videos/00324.mp4

threshold sweep:  23%|██▎       | 70/300 [21:52<1:11:51, 18.75s/it]

KeyboardInterrupt: